/*
 * Principal.java
 *
 */

package gui;

/**
 *
 * @author Arthur Thiago Barbosa Nobrega
 */
public class Principal extends javax.swing.JFrame {
    
    private final String TEXTOPADRAO = "Passe o mouse sobre a opção desejada para visualizar uma breve descrição da mesma.";
    
    /** Cria uma nova janela Principal. */
    public Principal() {
        initComponents();
        Containers.alinharContainer(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnTabela = new javax.swing.JButton();
        btnEquivalencia = new javax.swing.JButton();
        btnConsequencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAjuda = new javax.swing.JTextArea();
        txtAjuda.setText(TEXTOPADRAO);
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rela\u00e7\u00f5es entre F\u00f3rmulas Bem-Formadas");
        setResizable(false);
        btnTabela.setText("Tabela Verdade");
        btnTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabelaActionPerformed(evt);
            }
        });
        btnTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTabelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTabelaMouseExited(evt);
            }
        });

        btnEquivalencia.setText("Equival\u00eancia Sem\u00e2ntica");
        btnEquivalencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquivalenciaActionPerformed(evt);
            }
        });
        btnEquivalencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEquivalenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEquivalenciaMouseExited(evt);
            }
        });

        btnConsequencia.setText("Consequ\u00eancia L\u00f3gica");
        btnConsequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsequenciaActionPerformed(evt);
            }
        });
        btnConsequencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsequenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsequenciaMouseExited(evt);
            }
        });

        txtAjuda.setBackground(new java.awt.Color(226, 226, 226));
        txtAjuda.setColumns(20);
        txtAjuda.setEditable(false);
        txtAjuda.setLineWrap(true);
        txtAjuda.setRows(5);
        jScrollPane1.setViewportView(txtAjuda);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel1.setText(".: Escolha uma op\u00e7\u00e3o:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(btnTabela)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnEquivalencia)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnConsequencia))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnTabela)
                    .add(btnEquivalencia)
                    .add(btnConsequencia))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsequenciaActionPerformed
        new OpcaoConsequencia().setVisible(true);
    }//GEN-LAST:event_btnConsequenciaActionPerformed

    private void btnEquivalenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquivalenciaActionPerformed
        new OpcaoEquivalencia().setVisible(true);
    }//GEN-LAST:event_btnEquivalenciaActionPerformed

    private void btnTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabelaActionPerformed
        new OpcaoTabela().setVisible(true);
    }//GEN-LAST:event_btnTabelaActionPerformed

    private void btnConsequenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsequenciaMouseExited
        txtAjuda.setText(TEXTOPADRAO);
    }//GEN-LAST:event_btnConsequenciaMouseExited

    private void btnConsequenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsequenciaMouseEntered
        String texto = "Você poderá fornecer várias premissas (ou nenhuma) e uma " +
                "conclusão, então você saberá se aquela conclusão é uma consequência " +
                "lógica das premissas.";
        txtAjuda.setText(texto);
    }//GEN-LAST:event_btnConsequenciaMouseEntered

    private void btnEquivalenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEquivalenciaMouseExited
        txtAjuda.setText(TEXTOPADRAO);
    }//GEN-LAST:event_btnEquivalenciaMouseExited

    private void btnEquivalenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEquivalenciaMouseEntered
        String texto = "Você poderá fornecer duas fórmulas bem-formadas (FBF) e " +
                "testar se as duas têm as tabelas verdade iguais, ou seja, se as" +
                " duas fórmulas são equivalentes semânticamente.";
        txtAjuda.setText(texto);
    }//GEN-LAST:event_btnEquivalenciaMouseEntered

    private void btnTabelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTabelaMouseExited
        txtAjuda.setText(TEXTOPADRAO);
    }//GEN-LAST:event_btnTabelaMouseExited

    private void btnTabelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTabelaMouseEntered
        String texto = "Você poderá visualizar a tabela verdade de uma dada " +
                "fórmula bem-formada (FBF) que você fornecer.";
        txtAjuda.setText(texto);
    }//GEN-LAST:event_btnTabelaMouseEntered
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton btnConsequencia;
    private javax.swing.JButton btnEquivalencia;
    private javax.swing.JButton btnTabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAjuda;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
